# Generated by Django 5.2.1 on 2025-05-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
