# Generated by Django 5.2.4 on 2025-07-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
