# Generated by Django 5.2.4 on 2025-07-12 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_task_hora_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='task',
            name='hora_inicio',
        ),
        migrations.AlterField(
            model_name='task',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tareas.task')),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
    ]
